plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.13'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'org.openapi.generator' version '7.5.0'
}

group = 'com.evaluierung'
version = '0.0.1-SNAPSHOT'
description = 'REST API für Evaluierung'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-hateoas'
    implementation 'org.springdoc:springdoc-openapi-ui:1.8.0'
    implementation 'org.openapitools:jackson-databind-nullable:0.2.6'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    runtimeOnly 'com.h2database:h2'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
    useJUnitPlatform()
}
openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/openapi.yaml"
    outputDir = "$buildDir/generated/openapi"
    apiPackage = "com.evaluierung.api"
    modelPackage = "com.evaluierung.model"
    invokerPackage = "com.evaluierung"
    configOptions = [
        useSpringBoot3: "false",
        dateLibrary   : "java8",
        interfaceOnly : "true",
        useOptional   : "true",
    ]
}
task generateTypeScriptClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "typescript-fetch"
    inputSpec = "$rootDir/src/main/resources/openapi.yaml"
    outputDir = "$rootDir/../frontend/src/api"
    configOptions = [
        supportsES6: "true",
        modelPropertyNaming: "camelCase"
    ]
}
compileJava.dependsOn tasks.openApiGenerate
sourceSets.main.java.srcDir "$buildDir/generated/openapi/src/main/java"

tasks.named("build") {
    dependsOn(tasks.named("openApiGenerate"))
    dependsOn(generateTypeScriptClient)
}

