/* tslint:disable */
/* eslint-disable */
/**
 * Vehicle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface VehicleDto
 */
export interface VehicleDto {
    /**
     * 
     * @type {number}
     * @memberof VehicleDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'vehicleType': string;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'mileage': string;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'gearbox': string;
    /**
     * 
     * @type {number}
     * @memberof VehicleDto
     */
    'owner': number;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'kwAndPs': string;
    /**
     * 
     * @type {number}
     * @memberof VehicleDto
     */
    'hek': number;
    /**
     * 
     * @type {string}
     * @memberof VehicleDto
     */
    'taxation': string;
    /**
     * 
     * @type {object}
     * @memberof VehicleDto
     */
    '_links'?: object;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Alle Fahrzeuge abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vehicles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Alle Fahrzeuge abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vehiclesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<VehicleDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vehiclesGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         *
         * @summary Alle Fahrzeuge abrufen
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vehiclesGet(options?: any): AxiosPromise<Array<VehicleDto>> {
            return localVarFp.vehiclesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Alle Fahrzeuge abrufen
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public vehiclesGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).vehiclesGet(options).then((request) => request(this.axios, this.basePath));
    }
}


